#!/bin/bash
#version:	1.1
#license:	MIT
#author:	Simon Kowallik <github simonkowallik.com>
#source:	https://github.com/simonkowallik/iHAC
#
IHACAUTH="$HOME/.ihac/auth.jar"
IHACPROXYFILE="$HOME/.ihac/IHACPROXY"
if [[ -f "$IHACPROXYFILE" ]]; then IHACPROXY="$(<$IHACPROXYFILE)"; fi
if [[ ! -z "$IHACPROXY" ]]; then IHACPROXY="-x $IHACPROXY"; fi

function echoerr() { echo "$@" 1>&2; }

if [[ -n "$1" ]] && [[ "$1" =~ ^[0-9]+$ ]]
then
  if [[ -n "$2" ]]
  then
    curl $IHACPROXY --progress-bar -H"Accept: application/vnd.f5.ihealth.api.v1.0" --user-agent "iHAC/1.0" \
     --cookie "$IHACAUTH" --cookie-jar "$IHACAUTH" \
     -o - https://ihealth-api.f5.com/qkview-analyzer/api/qkviews/$1/files/qkview \
    > $2
    if [[ $? -eq 0 ]]; then echo "OK"; fi
  elif [[ ! -t 1 ]]
  then
    curl $IHACPROXY --progress-bar -H"Accept: application/vnd.f5.ihealth.api.v1.0" --user-agent "iHAC/1.0" \
     --cookie "$IHACAUTH" --cookie-jar "$IHACAUTH" \
     -o - https://ihealth-api.f5.com/qkview-analyzer/api/qkviews/$1/files/qkview
  else
    echoerr "Error: no output file specified and no i/o redirection."
    echoerr "Use: `basename $0` ID /path/file"
    echoerr "Use: `basename $0` ID > /path/file"
    echoerr "Use: `basename $0` ID | command"
    exit 1
  fi
else
  echoerr "Error: no qkview ID specified or not valid."
  echoerr "Use: `basename $0` ID /path/file"
  echoerr "Use: `basename $0` ID > /path/file"
  echoerr "Use: `basename $0` ID | command"
  exit 1
fi