#!/usr/bin/env bash
#license:	MIT
#author:	Simon Kowallik <github simonkowallik.com>
#source:	https://github.com/simonkowallik/iHAC
VERSION="3.2"
#
IHACAUTH="$HOME/.ihac/auth.jar"
IHACPROXYFILE="$HOME/.ihac/IHACPROXY"
if [[ -f "$IHACPROXYFILE" ]]; then IHACPROXY="$(<$IHACPROXYFILE)"; fi
if [[ ! -z "$IHACPROXY" ]]; then IHACPROXY="x $IHACPROXY"; fi

function echoerr() { echo "$@" 1>&2; }

command -v perl >/dev/null 2>&1 || { echoerr "Error: $(basename $0) requires perl but it is not installed."; exit 1; }
command -v curl >/dev/null 2>&1 || { echoerr "Error: $(basename $0) requires curl but it is not installed."; exit 1; }

if [[ -n "$1" ]] && [[ "$1" =~ ^[0-9]+$ ]] && [[ -n "$2" ]]
then
  if command -v sha1sum > /dev/null
  then
	cmdid=(`echo -n $2 | sha1sum`)
  else
	cmdid=(`echo -n $2 | shasum`)
  fi
  curl -si$IHACPROXY -H"Accept: application/vnd.f5.ihealth.api.v1.0" --user-agent "iHAC/$VERSION" \
   --cookie "$IHACAUTH" --cookie-jar "$IHACAUTH" \
   -o - https://ihealth-api.f5.com/qkview-analyzer/api/qkviews/$1/commands/${cmdid[0]} \
  | perl -MMIME::Base64 -ne 's/[\r\n]+//g;
	if(m|http/1.. 200|gi) {$ok=1} else {
	if(m|http/1.. 30\d|gi) {print STDERR "Error: not authenticated.\n";exit 1}
	if(m|http/1.. 404|gi)  {print STDERR "Error: no command list received, qkview ID might not exist.\n";exit 1}
	if(m|http/1.. 500|gi)  {print STDERR "Error: received code 500 from server. Command might not exist.\n";exit 1}
	} if($ok && m/<\?xml/gi) {foreach(split /></) {if(m|output>(.+)</output|gi) {print decode_base64($1)}} exit 0}'
else
  if [[ -n "$1" ]] && [[ $1 =~ ^[0-9]+$ ]]
  then
	echoerr "Error: no qkview ID specified or not valid."
  else
    echoerr "Error: no command specified."
  fi
  echoerr "Use: `basename $0` ID 'command'"
  exit 1
fi