#!/bin/bash
#version:	2.0
#license:	MIT
#author:	Simon Kowallik <github simonkowallik.com>
#source:	https://github.com/simonkowallik/iHAC
#
IHACAUTH="$HOME/.ihac/auth.jar"
IHACPROXYFILE="$HOME/.ihac/IHACPROXY"
if [[ -f "$IHACPROXYFILE" ]]; then IHACPROXY="$(<$IHACPROXYFILE)"; fi
if [[ ! -z "$IHACPROXY" ]]; then IHACPROXY="x $IHACPROXY"; fi

function echoerr() { echo "$@" 1>&2; }

command -v perl >/dev/null 2>&1 || { echoerr "Error: $(basename $0) requires perl but it is not installed."; exit 1; }
command -v curl >/dev/null 2>&1 || { echoerr "Error: $(basename $0) requires curl but it is not installed."; exit 1; }

if [[ "$#" -gt 0 ]]
then
  QKVIEWS=("$@")
elif [[ ! -t 0 ]]
then
  QKVIEWS="-"
else	
  echoerr "Error: no file specified"
  echoerr "Use: `basename $0` /path/file [/path/fileN]"
  echoerr "Use: cat /path/file | `basename $0`"
  exit 1
fi

for QKVIEW in "${QKVIEWS[@]}"; do
if [[ -f "$QKVIEW" ]] || [[ "$QKVIEW" == "-" ]]; then
curl --progress-bar -i$IHACPROXY -H"Accept: application/vnd.f5.ihealth.api.v1.0" --user-agent "iHAC/2.0" \
 --cookie "$IHACAUTH" --cookie-jar "$IHACAUTH" \
 -F "qkview=@$QKVIEW" -F 'visible_in_gui=True' \
 -o - https://ihealth-api.f5.com/qkview-analyzer/api/qkviews \
 | perl -ne 's/\r\n//g;
 	if(m|http/1.. 303|gi) {$ok=1} else {
 	if(m|http/1.. 30\d|gi) {print STDERR "Error: not authenticated.\n";exit 1}
 	if(m|http/1.. (40\d)|gi) {print STDERR "Error: received '$1' response from server.\n";exit 1}
 	} if($ok && m/^location/gi) {if(m|.+/qkviews/(\d+)$|gi) {$qkid=$1}}
	  if($ok && m/<\?xml/gi) {if(m|<result>(.+)</result>|gi) {print "$qkid $1\n"} exit 0}'
else
  echoerr "Error: '$QKVIEW' not a file or does not exist."
fi
done