#!/bin/bash
#version:	1.0
#license:	MIT
#author:	Simon Kowallik <github simonkowallik.com>
#source:	https://github.com/simonkowallik/iHAC
#
IHACAUTH=$HOME/.ihac/auth.jar
IHACPROXYFILE=$HOME/.ihac/IHACPROXY
if [ -f $IHACPROXYFILE ]; then IHACPROXY="$(<$IHACPROXYFILE)"; fi
if [ ! -z "$IHACPROXY" ]; then IHACPROXY="x $IHACPROXY"; fi

function echoerr() { echo "$@" 1>&2; }

if [ -e "$1" ] && [ -n "$1" ]
then
  QKVIEW="$1"
elif [ ! -t 0 ]
then
  QKVIEW="-"
else
  echoerr 'Error: no file specified'
  echoerr "Use: `basename $0` /path/file"
  echoerr "Use: cat /path/file | `basename $0`"
  exit 1
fi

curl --progress-bar -i$IHACPROXY -H"Accept: application/vnd.f5.ihealth.api.v1.0" --user-agent "iHAC/1.0" \
 --cookie $IHACAUTH --cookie-jar $IHACAUTH \
 -F "qkview=@$QKVIEW" -F 'visible_in_gui=True' \
 -o - https://ihealth-api.f5.com/qkview-analyzer/api/qkviews \
 | perl -ne 's/\r\n//g;
	if(m|http/1.. 303|gi) {$ok=1} else {
	if(m|http/1.. 30\d|gi) {print STDERR "Error: not authenticated.\n";exit 1}
	if(m|http/1.. (40\d)|gi) {print STDERR "Error: received $1 from server.\n";exit 1}
	} if($ok && m/<\?xml/gi) { if(m|<result>(.+)</result>|gi) {print "$1\n"} exit 0}'