#!/bin/bash
#version:	1.2
#license:	MIT
#author:	Simon Kowallik <github simonkowallik.com>
#source:	https://github.com/simonkowallik/iHAC
#
IHACAUTH="$HOME/.ihac/auth.jar"
IHACPROXYFILE="$HOME/.ihac/IHACPROXY"
if [[ -f "$IHACPROXYFILE" ]]; then IHACPROXY="$(<$IHACPROXYFILE)"; fi
if [[ ! -z "$IHACPROXY" ]]; then IHACPROXY="x $IHACPROXY"; fi

function echoerr() { echo "$@" 1>&2; }

if [[ -n "$1" ]] && [[ "$1" =~ ^[0-9]+$ ]]
then
  curl -si$IHACPROXY -H"Accept: application/vnd.f5.ihealth.api.v1.0" --user-agent "iHAC/1.0" \
   --cookie "$IHACAUTH" --cookie-jar "$IHACAUTH" \
   -o - https://ihealth-api.f5.com/qkview-analyzer/api/qkviews/$1/files \
  | perl -ne 's/\r\n//g;
	if(m|http/1.. 200|gi) {$ok=1} else {
	if(m|http/1.. 30\d|gi) {print STDERR "Error: not authenticated.\n";exit 1}
	if(m|http/1.. 404|gi)  {print STDERR "Error: no file list received, qkview ID might not exist.\n";exit 1}
	} if($ok && m/<\?xml/gi) {foreach(split /></) {if(m|file.+>(.+)</file|gi) {print "$1\n"}} exit 0}'
else
  echoerr "Error: no qkview ID specified or not valid."
  echoerr "Use: `basename $0` ID"
  exit 1
fi